### ISSUE TITLE
横屏状态长按 p 会 crash，必现。

### ISSUE THREAD

**Issue by 7sDream** [fcitx5-android/fcitx5-android#252]
但是竖屏状态正常，可以显示 popup 并正常选择输入。

<details><summary>stack backtrace：</summary>

```
--------- Device Info
OS Name: MyOS13.0.14MR3_NX712J
OS Version: 5.15.41-android13-8-00024-g3605981d8a31-ab9291366 (20230414.172241)
OS API Level: 33
Device: PQ82A11
Model (product): NX712J (CN_PQ82A11)
Manufacturer: nubia
Tags: release-keys
Screen Size: 1116 x 2390
Screen Density: 3.0
Screen orientation: Portrait
--------- Build Info
Package Name: org.fcitx.fcitx5.android
Version Code: 32
Version Name: 0.0.5-0-g679ab7db-release
Build Time: 2023-03-20T18:56:18Z
Build Git Hash: 679ab7dbcf3ea21af1ba4785acbb591dedb5b9de
--------- Crash stacktrace
java.lang.ArrayIndexOutOfBoundsException: length=2; index=2
	at org.fcitx.fcitx5.android.input.popup.PopupContainerUi.createColumnOrder(PopupContainerUi.kt:4)
	at org.fcitx.fcitx5.android.input.popup.PopupKeyboardUi.<init>(PopupKeyboardUi.kt:119)
	at org.fcitx.fcitx5.android.input.popup.PopupComponent$$ExternalSyntheticLambda0.onPopupAction(R8$$SyntheticClass:359)
	at org.fcitx.fcitx5.android.input.keyboard.TextKeyboard.onPopupAction(TextKeyboard.kt:111)
	at org.fcitx.fcitx5.android.input.keyboard.BaseKeyboard$$ExternalSyntheticLambda8.onLongClick(R8$$SyntheticClass:37)
	at android.view.View.performLongClickInternal(View.java:7649)
	at android.view.View.performLongClick(View.java:7607)
	at org.fcitx.fcitx5.android.input.keyboard.CustomGestureView$onTouchEvent$1.invokeSuspend(CustomGestureView.kt:51)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:48)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:129)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:44)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:24)
	at kotlinx.coroutines.android.HandlerContext$scheduleResumeAfterDelay$$inlined$Runnable$1.run(Runnable.kt:7)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:234)
	at android.os.Looper.loop(Looper.java:346)
	at android.app.ActivityThread.main(ActivityThread.java:8595)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@52d8168, Dispatchers.Main.immediate]

--------- beginning of main
D/NavigationColorHandlerZte( 6323): onWindowShown, service = org.fcitx.fcitx5.android.input.FcitxInputMethodService@1ec14f6
W/NavigationColorHandlerZte( 6323): Object tried to add another service:org.fcitx.fcitx5.android.input.FcitxInputMethodService@1ec14f6
D/Dialog  ( 6323): show in ... mOwnerActivity = null
D/NavigationColorHandlerZte( 6323): updateColor, service = org.fcitx.fcitx5.android.input.FcitxInputMethodService@1ec14f6
E/FrameEvents( 6323): updateAcquireFence: Did not find frame.
D/NavigationColorHandlerZte( 6323): updateColorInternal bitmap w = 1116, h = 2381, navi h = 120
D/NavigationColorHandlerZte( 6323): updateColorInternal swatchesSize = 2
D/NavigationColorHandlerZte( 6323): updateColorInternal, primary = 0xffe8e8e8, secondary = 0xff74a5f7
D/NavigationColorHandlerZte( 6323): onWindowShown, service = org.fcitx.fcitx5.android.input.FcitxInputMethodService@1ec14f6
W/NavigationColorHandlerZte( 6323): Object tried to add another service:org.fcitx.fcitx5.android.input.FcitxInputMethodService@1ec14f6
D/Dialog  ( 6323): show in ... mOwnerActivity = null
D/NavigationColorHandlerZte( 6323): updateColor, service = org.fcitx.fcitx5.android.input.FcitxInputMethodService@1ec14f6
E/FrameEvents( 6323): updateAcquireFence: Did not find frame.
D/NavigationColorHandlerZte( 6323): updateColorInternal bitmap w = 1116, h = 2381, navi h = 120
D/NavigationColorHandlerZte( 6323): updateColorInternal swatchesSize = 2
D/NavigationColorHandlerZte( 6323): updateColorInternal, primary = 0xffe8e8e8, secondary = 0xff74a5f7
D/NavigationColorHandlerZte( 6323): onWindowShown, service = org.fcitx.fcitx5.android.input.FcitxInputMethodService@1ec14f6
W/NavigationColorHandlerZte( 6323): Object tried to add another service:org.fcitx.fcitx5.android.input.FcitxInputMethodService@1ec14f6
D/Dialog  ( 6323): show in ... mOwnerActivity = null
D/NavigationColorHandlerZte( 6323): updateColor, service = org.fcitx.fcitx5.android.input.FcitxInputMethodService@1ec14f6
E/FrameEvents( 6323): updateAcquireFence: Did not find frame.
D/NavigationColorHandlerZte( 6323): updateColorInternal bitmap w = 1116, h = 2381, navi h = 120
D/NavigationColorHandlerZte( 6323): updateColorInternal swatchesSize = 2
D/NavigationColorHandlerZte( 6323): updateColorInternal, primary = 0xffececec, secondary = 0xff74a5f7
E/FrameEvents( 6323): updateAcquireFence: Did not find frame.
D/NavigationColorHandlerZte( 6323): updateColorInternal bitmap w = 1116, h = 2381, navi h = 120
D/NavigationColorHandlerZte( 6323): updateColorInternal swatchesSize = 2
D/NavigationColorHandlerZte( 6323): updateColorInternal, primary = 0xffececec, secondary = 0xff74a5f7
E/FrameEvents( 6323): updateAcquireFence: Did not find frame.
D/NavigationColorHandlerZte( 6323): updateColorInternal bitmap w = 1116, h = 2381, navi h = 120
D/NavigationColorHandlerZte( 6323): updateColorInternal swatchesSize = 2
D/NavigationColorHandlerZte( 6323): updateColorInternal, primary = 0xffececec, secondary = 0xff74a5f7
E/FrameEvents( 6323): updateAcquireFence: Did not find frame.
D/NavigationColorHandlerZte( 6323): updateColorInternal bitmap w = 1116, h = 2381, navi h = 120
D/NavigationColorHandlerZte( 6323): updateColorInternal swatchesSize = 2
D/NavigationColorHandlerZte( 6323): updateColorInternal, primary = 0xffececec, secondary = 0xff74a5f7
E/FrameEvents( 6323): updateAcquireFence: Did not find frame.
D/NavigationColorHandlerZte( 6323): updateColorInternal bitmap w = 1116, h = 2381, navi h = 120
D/NavigationColorHandlerZte( 6323): updateColorInternal swatchesSize = 2
D/NavigationColorHandlerZte( 6323): updateColorInternal, primary = 0xffececec, secondary = 0xff74a5f7
E/FrameEvents( 6323): updateAcquireFence: Did not find frame.
D/NavigationColorHandlerZte( 6323): updateColorInternal bitmap w = 1116, h = 2381, navi h = 120
D/NavigationColorHandlerZte( 6323): updateColorInternal swatchesSize = 2
D/NavigationColorHandlerZte( 6323): updateColorInternal, primary = 0xffececec, secondary = 0xff74a5f7
E/FrameEvents( 6323): updateAcquireFence: Did not find frame.
D/NavigationColorHandlerZte( 6323): updateColorInternal bitmap w = 1116, h = 2381, navi h = 120
D/NavigationColorHandlerZte( 6323): updateColorInternal swatchesSize = 2
D/NavigationColorHandlerZte( 6323): updateColorInternal, primary = 0xffececec, secondary = 0xff74a5f7
D/NavigationColorHandlerZte( 6323): onWindowHidden, service = org.fcitx.fcitx5.android.input.FcitxInputMethodService@1ec14f6
D/NavigationColorHandlerZte( 6323): removeWindow end, size = 0
D/Dialog  ( 6323): hide in ... mOwnerActivity = null
D/Service ( 6323): services onConfigurationChanged customFont:/data/resource-cache/font/FT5d64ec87e4b089bf70ee4442
D/NavigationColorHandlerZte( 6323): updateColor, service = org.fcitx.fcitx5.android.input.FcitxInputMethodService@1ec14f6
D/Z##OverScrollerMifavor( 6323): SplineOverScroller mStringID = [6001] , this = android.widget.OverScroller$SplineOverScroller@cf06001
D/Z##OverScrollerMifavor( 6323): SplineOverScroller mStringID = [5ea6] , this = android.widget.OverScroller$SplineOverScroller@15f5ea6
D/Z##OverScrollerMifavor( 6323): new SplineOverScroller.SMART_SLIDE in OverScroller. mScrollerX = android.widget.OverScroller$SplineOverScroller@cf06001, mScrollerY = android.widget.OverScroller$SplineOverScroller@15f5ea6
D/Z##OverScrollerMifavor( 6323): SplineOverScroller mStringID = [10e7] , this = android.widget.OverScroller$SplineOverScroller@ed610e7
D/Z##OverScrollerMifavor( 6323): SplineOverScroller mStringID = [c494] , this = android.widget.OverScroller$SplineOverScroller@3f5c494
D/Z##OverScrollerMifavor( 6323): new SplineOverScroller.SMART_SLIDE in OverScroller. mScrollerX = android.widget.OverScroller$SplineOverScroller@ed610e7, mScrollerY = android.widget.OverScroller$SplineOverScroller@3f5c494
D/NavigationColorHandlerZte( 6323): updateColor, service = org.fcitx.fcitx5.android.input.FcitxInputMethodService@1ec14f6
D/NavigationColorHandlerZte( 6323): onWindowShown, service = org.fcitx.fcitx5.android.input.FcitxInputMethodService@1ec14f6
D/NavigationColorHandlerZte( 6323): removeWindow end, size = 1
D/NavigationColorHandlerZte( 6323): registerWindow end, size = 1
D/Dialog  ( 6323): show in ... mOwnerActivity = null
D/NavigationColorHandlerZte( 6323): updateColor, service = org.fcitx.fcitx5.android.input.FcitxInputMethodService@1ec14f6
E/FrameEvents( 6323): updateAcquireFence: Did not find frame.
D/NavigationColorHandlerZte( 6323): updateColorInternal bitmap w = 1116, h = 2381, navi h = 120
D/NavigationColorHandlerZte( 6323): updateColorInternal swatchesSize = 1
D/NavigationColorHandlerZte( 6323): updateColorInternal, primary = 0xff000000, secondary = NULL
D/NavigationColorHandlerZte( 6323): updateColorInternal, fail to get bg color
E/.fcitx5.android( 6323): No package ID ff found for ID 0xffffffff.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffffffff
E/.fcitx5.android( 6323): No package ID ff found for ID 0xffffffff.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffffffff
E/.fcitx5.android( 6323): No package ID ff found for ID 0xffffffff.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffffffff
E/.fcitx5.android( 6323): Invalid ID 0x00ffff5e.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff5e
E/.fcitx5.android( 6323): Invalid ID 0x00ffff5f.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff5f
E/.fcitx5.android( 6323): Invalid ID 0x00ffff5d.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff5d
E/.fcitx5.android( 6323): Invalid ID 0x00ffff5c.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff5c
E/.fcitx5.android( 6323): Invalid ID 0x00ffff5b.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff5b
E/.fcitx5.android( 6323): Invalid ID 0x00ffff5a.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff5a
E/.fcitx5.android( 6323): Invalid ID 0x00ffff59.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff59
E/.fcitx5.android( 6323): Invalid ID 0x00ffff58.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff58
E/.fcitx5.android( 6323): Invalid ID 0x00ffff57.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff57
E/.fcitx5.android( 6323): Invalid ID 0x00ffff56.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff56
E/.fcitx5.android( 6323): Invalid ID 0x00ffff51.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff51
E/.fcitx5.android( 6323): Invalid ID 0x00ffff98.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff98
E/.fcitx5.android( 6323): Invalid ID 0x00ffff98.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff98
E/.fcitx5.android( 6323): Invalid ID 0x00ffff99.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff99
E/.fcitx5.android( 6323): Invalid ID 0x00ffff99.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff99
E/.fcitx5.android( 6323): Invalid ID 0x00ffff97.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff97
E/.fcitx5.android( 6323): Invalid ID 0x00ffff97.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff97
E/.fcitx5.android( 6323): Invalid ID 0x00ffff96.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff96
E/.fcitx5.android( 6323): Invalid ID 0x00ffff96.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff96
E/.fcitx5.android( 6323): Invalid ID 0x00ffff95.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff95
E/.fcitx5.android( 6323): Invalid ID 0x00ffff95.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff95
E/.fcitx5.android( 6323): Invalid ID 0x00ffff94.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff94
E/.fcitx5.android( 6323): Invalid ID 0x00ffff94.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff94
E/.fcitx5.android( 6323): Invalid ID 0x00ffff93.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff93
E/.fcitx5.android( 6323): Invalid ID 0x00ffff93.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff93
E/.fcitx5.android( 6323): Invalid ID 0x00ffff92.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff92
E/.fcitx5.android( 6323): Invalid ID 0x00ffff92.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff92
E/.fcitx5.android( 6323): Invalid ID 0x00ffff91.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff91
E/.fcitx5.android( 6323): Invalid ID 0x00ffff91.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff91
E/.fcitx5.android( 6323): Invalid ID 0x00ffff90.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff90
E/.fcitx5.android( 6323): Invalid ID 0x00ffff90.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff90
E/.fcitx5.android( 6323): Invalid ID 0x00ffff8e.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff8e
E/.fcitx5.android( 6323): Invalid ID 0x00ffff8e.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff8e
E/.fcitx5.android( 6323): Invalid ID 0x00ffff8f.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff8f
E/.fcitx5.android( 6323): Invalid ID 0x00ffff8f.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff8f
E/.fcitx5.android( 6323): Invalid ID 0x00ffff8d.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff8d
E/.fcitx5.android( 6323): Invalid ID 0x00ffff8d.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff8d
E/.fcitx5.android( 6323): Invalid ID 0x00ffff8c.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff8c
E/.fcitx5.android( 6323): Invalid ID 0x00ffff8c.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff8c
E/.fcitx5.android( 6323): Invalid ID 0x00ffff8b.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff8b
E/.fcitx5.android( 6323): Invalid ID 0x00ffff8b.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff8b
E/.fcitx5.android( 6323): Invalid ID 0x00ffff8a.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff8a
E/.fcitx5.android( 6323): Invalid ID 0x00ffff8a.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff8a
E/.fcitx5.android( 6323): Invalid ID 0x00ffff89.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff89
E/.fcitx5.android( 6323): Invalid ID 0x00ffff89.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff89
E/.fcitx5.android( 6323): Invalid ID 0x00ffff88.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff88
E/.fcitx5.android( 6323): Invalid ID 0x00ffff88.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff88
E/.fcitx5.android( 6323): Invalid ID 0x00ffff87.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff87
E/.fcitx5.android( 6323): Invalid ID 0x00ffff87.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff87
E/.fcitx5.android( 6323): Invalid ID 0x00ffff86.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff86
E/.fcitx5.android( 6323): Invalid ID 0x00ffff86.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff86
E/.fcitx5.android( 6323): Invalid ID 0x00ffff85.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff85
E/.fcitx5.android( 6323): Invalid ID 0x00ffff85.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff85
E/.fcitx5.android( 6323): Invalid ID 0x00ffff84.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff84
E/.fcitx5.android( 6323): Invalid ID 0x00ffff84.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff84
E/.fcitx5.android( 6323): Invalid ID 0x00ffff83.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff83
E/.fcitx5.android( 6323): Invalid ID 0x00ffff83.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff83
E/.fcitx5.android( 6323): Invalid ID 0x00ffff82.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff82
E/.fcitx5.android( 6323): Invalid ID 0x00ffff82.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff82
E/.fcitx5.android( 6323): Invalid ID 0x00ffff81.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff81
E/.fcitx5.android( 6323): Invalid ID 0x00ffff81.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff81
E/.fcitx5.android( 6323): Invalid ID 0x00ffff80.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff80
E/.fcitx5.android( 6323): Invalid ID 0x00ffff80.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff80
E/.fcitx5.android( 6323): Invalid ID 0x00ffff7e.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff7e
E/.fcitx5.android( 6323): Invalid ID 0x00ffff7f.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff7f
E/.fcitx5.android( 6323): Invalid ID 0x00ffff7d.
D/TextView( 6323): onConfigurationChanged e:android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffff7d
D/NavigationColorHandlerZte( 6323): onWindowShown, service = org.fcitx.fcitx5.android.input.FcitxInputMethodService@1ec14f6
W/NavigationColorHandlerZte( 6323): Object tried to add another service:org.fcitx.fcitx5.android.input.FcitxInputMethodService@1ec14f6
D/Dialog  ( 6323): show in ... mOwnerActivity = null
D/NavigationColorHandlerZte( 6323): updateColor, service = org.fcitx.fcitx5.android.input.FcitxInputMethodService@1ec14f6
E/FrameEvents( 6323): updateAcquireFence: Did not find frame.
D/NavigationColorHandlerZte( 6323): updateColorInternal bitmap w = 2480, h = 1116, navi h = 120
D/NavigationColorHandlerZte( 6323): updateColorInternal swatchesSize = 2
D/NavigationColorHandlerZte( 6323): updateColorInternal, primary = 0xfff2f2f2, secondary = 0xff4285f4
E/FrameEvents( 6323): updateAcquireFence: Did not find frame.
D/NavigationColorHandlerZte( 6323): updateColorInternal bitmap w = 2480, h = 1116, navi h = 120
D/NavigationColorHandlerZte( 6323): updateColorInternal swatchesSize = 2
D/NavigationColorHandlerZte( 6323): updateColorInternal, primary = 0xfff2f2f2, secondary = 0xff4285f4
E/FrameEvents( 6323): updateAcquireFence: Did not find frame.
D/NavigationColorHandlerZte( 6323): updateColorInternal bitmap w = 2480, h = 1116, navi h = 120
D/NavigationColorHandlerZte( 6323): updateColorInternal swatchesSize = 2
D/NavigationColorHandlerZte( 6323): updateColorInternal, primary = 0xfff2f2f2, secondary = 0xff4285f4
E/FrameEvents( 6323): updateAcquireFence: Did not find frame.
D/NavigationColorHandlerZte( 6323): updateColorInternal bitmap w = 2480, h = 1116, navi h = 120
D/NavigationColorHandlerZte( 6323): updateColorInternal swatchesSize = 2
D/NavigationColorHandlerZte( 6323): updateColorInternal, primary = 0xfff2f2f2, secondary = 0xff4285f4
E/FrameEvents( 6323): updateAcquireFence: Did not find frame.
D/NavigationColorHandlerZte( 6323): updateColorInternal bitmap w = 2480, h = 1116, navi h = 120
D/NavigationColorHandlerZte( 6323): updateColorInternal swatchesSize = 2
D/NavigationColorHandlerZte( 6323): updateColorInternal, primary = 0xfff2f2f2, secondary = 0xff4285f4
E/FrameEvents( 6323): updateAcquireFence: Did not find frame.
D/NavigationColorHandlerZte( 6323): updateColorInternal bitmap w = 2480, h = 1116, navi h = 120
D/NavigationColorHandlerZte( 6323): updateColorInternal swatchesSize = 2
D/NavigationColorHandlerZte( 6323): updateColorInternal, primary = 0xfff2f2f2, secondary = 0xff4285f4
V/InputEventReceiver( 6323): onInputEvent MotionEvent.getDeviceId:6
V/InputEventReceiver( 6323): mInputMethodMgr.setRemotePc to false
D/VRI[InputMethod]( 6323): processPointerEvent: action: ACTION_DOWN, handled = true, X=729.6691, Y=1043.254
V/InputEventReceiver( 6323): onInputEvent MotionEvent.getDeviceId:6
V/InputEventReceiver( 6323): mInputMethodMgr.setRemotePc to false
D/VRI[InputMethod]( 6323): processPointerEvent: action: ACTION_UP, handled = true, X=729.6691, Y=1043.254
V/InputEventReceiver( 6323): onInputEvent MotionEvent.getDeviceId:6
V/InputEventReceiver( 6323): mInputMethodMgr.setRemotePc to false
D/VRI[InputMethod]( 6323): processPointerEvent: action: ACTION_DOWN, handled = true, X=2339.066, Y=585.6547
I/.fcitx5.android( 6323): System.exit called, status: 10
I/AndroidRuntime( 6323): VM exiting with result code 10, cleanup skipped.
```
</details>

**Comment by rocka** [comment]
能不能发一下你的主题设置以及键盘横屏/竖屏的截图？我这里无法复现

**Comment by rocka** [comment]
无法复现故关闭。
