### ISSUE TITLE
在应用内添加搜狗细胞词库时崩溃

### ISSUE THREAD

**Issue by du33169** [fcitx5-android/fcitx5-android#320]
**描述问题 / Describe the bug**

在输入法内添加拼音词典时，选择搜狗细胞词库文件时会直接崩溃闪退
**重现步骤 / To Reproduce**

1. 打开输入法主页面，点击“附加组件”
2. 点击 “拼音”
3. 点击“词典”
4. 点击浮动+号按钮，弹出文件选择器
5. 选择词典文件
6. 崩溃闪退

**预期的行为 / Expected behavior**

正常导入词典
**日志 / Log**

日志如下，主要报错是uri错误，猜测可能与安卓13的文件访问权限有关
<details><summary>日志</summary>

```
--------- Device Info
OS Name: MyOS13.0.17MR6_NX712J
OS Version: 5.15.41-android13-8-00024-g3605981d8a31-ab9291366 (20230724.190543)
OS API Level: 33
Device: PQ82A11
Model (product): NX712J (CN_PQ82A11)
Manufacturer: nubia
Tags: release-keys
Screen Size: 1116 x 2480
Screen Density: 3.0
Screen orientation: Portrait
--------- Build Info
Package Name: org.fcitx.fcitx5.android
Version Code: 42
Version Name: 0.0.6-0-g024241cf-release
Build Time: 2023-06-12T09:17:36Z
Build Git Hash: 024241cff19ca4bd79a3a6df511053c4c3aada29
--------- Crash stacktrace
java.lang.IllegalArgumentException: You must pass a valid uri and observer
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:481)
	at android.content.ContentResolver.query(ContentResolver.java:1231)
	at android.content.ContentResolver.query(ContentResolver.java:1157)
	at android.content.ContentResolver.query(ContentResolver.java:1113)
	at org.fcitx.fcitx5.android.utils.UtilsKt.queryFileName(SourceFile:12)
	at org.fcitx.fcitx5.android.ui.main.settings.PinyinDictionaryFragment$importFromUri$1$invokeSuspend$$inlined$invoke$1.invokeSuspend(SourceFile:132)
	at org.fcitx.fcitx5.android.ui.main.settings.PinyinDictionaryFragment$importFromUri$1$invokeSuspend$$inlined$invoke$1.invoke(SourceFile:13)
	at arrow.core.continuations.DefaultEffect$fold$4$fold$1.invokeSuspend(SourceFile:42)
	at arrow.core.continuations.DefaultEffect$fold$4$fold$1.invoke(SourceFile:13)
	at kotlin.TuplesKt.toOption(SourceFile:40)
	at org.fcitx.fcitx5.android.ui.main.settings.PinyinDictionaryFragment$importFromUri$1.invokeSuspend(SourceFile:61)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:114)
	at androidx.core.app.ActivityRecreator$1.run(SourceFile:190)
	at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:94)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@b1d4136, Dispatchers.IO]

--------- beginning of system
D/ActivityThread( 4512): ***** handleLaunchActivity ActivityRecord{e61e330 token=android.os.BinderProxy@2535873 {org.fcitx.fcitx5.android/org.fcitx.fcitx5.android.ui.main.MainActivity}}
D/ActivityThread( 4512): ***** handleStartActivity ActivityRecord{e61e330 token=android.os.BinderProxy@2535873 {org.fcitx.fcitx5.android/org.fcitx.fcitx5.android.ui.main.MainActivity}} stopped= true paused= true mFinished= false
D/ActivityThread( 4512): ***** performResumeActivity ActivityRecord{e61e330 token=android.os.BinderProxy@2535873 {org.fcitx.fcitx5.android/org.fcitx.fcitx5.android.ui.main.MainActivity}} mFinished= false
D/ActivityThread( 4512): ***** performPauseActivity ActivityRecord{e61e330 token=android.os.BinderProxy@2535873 {org.fcitx.fcitx5.android/org.fcitx.fcitx5.android.ui.main.MainActivity}} finished= false paused= false mFinished= false
D/ActivityThread( 4512): ***** handleStopActivity r ActivityRecord{e61e330 token=android.os.BinderProxy@2535873 {org.fcitx.fcitx5.android/org.fcitx.fcitx5.android.ui.main.MainActivity}} stopped= false paused= true
--------- beginning of main
D/Dialog  ( 4512): hide in ... mOwnerActivity = null
D/Dialog  ( 4512): hide in ... mOwnerActivity = null
D/Dialog  ( 4512): hide in ... mOwnerActivity = null
D/Dialog  ( 4512): hide in ... mOwnerActivity = null
D/Dialog  ( 4512): hide in ... mOwnerActivity = null
D/Dialog  ( 4512): hide in ... mOwnerActivity = null
D/ActivityThread( 4512): ***** handleStartActivity ActivityRecord{e61e330 token=android.os.BinderProxy@2535873 {org.fcitx.fcitx5.android/org.fcitx.fcitx5.android.ui.main.MainActivity}} stopped= true paused= true mFinished= false
I/Dialog  ( 4512): Dialog:  org.fcitx.fcitx5.android
I/Dialog  ( 4512): Dialog:  org.fcitx.fcitx5.android
D/Dialog  ( 4512): show in ... mOwnerActivity = null
D/Z##OverScrollerMifavor( 4512): SplineOverScroller mStringID = [17a5] , this = android.widget.OverScroller$SplineOverScroller@7b217a5
D/Z##OverScrollerMifavor( 4512): SplineOverScroller mStringID = [877a] , this = android.widget.OverScroller$SplineOverScroller@8a6877a
D/Z##OverScrollerMifavor( 4512): new SplineOverScroller.SMART_SLIDE in OverScroller. mScrollerX = android.widget.OverScroller$SplineOverScroller@7b217a5, mScrollerY = android.widget.OverScroller$SplineOverScroller@8a6877a
D/Z##OverScrollerMifavor( 4512): SplineOverScroller mStringID = [8921] , this = android.widget.OverScroller$SplineOverScroller@6d18921
D/Z##OverScrollerMifavor( 4512): SplineOverScroller mStringID = [a146] , this = android.widget.OverScroller$SplineOverScroller@f85a146
D/Z##OverScrollerMifavor( 4512): new SplineOverScroller.SMART_SLIDE in OverScroller. mScrollerX = android.widget.OverScroller$SplineOverScroller@6d18921, mScrollerY = android.widget.OverScroller$SplineOverScroller@f85a146
D/WindowClient( 4512): Add to mViews: DecorView@21c965d[MainActivity], this = android.view.WindowManagerGlobal@43593e3mViews.size()=3
D/WindowClient( 4512): Add to mViews packageName:org.fcitx.fcitx5.android
D/ActivityThread( 4512): ***** performResumeActivity ActivityRecord{e61e330 token=android.os.BinderProxy@2535873 {org.fcitx.fcitx5.android/org.fcitx.fcitx5.android.ui.main.MainActivity}} mFinished= false
W/Parcel  ( 4512): Expecting binder but got null!
D/Dialog  ( 4512): hide in ... mOwnerActivity = null
V/InputEventReceiver( 4512): onInputEvent MotionEvent.getDeviceId:6
V/InputEventReceiver( 4512): mInputMethodMgr.setRemotePc to false
D/VRI[MainActivity]( 4512): processPointerEvent: action: ACTION_DOWN, handled = true, X=905.3227, Y=438.40137
V/InputEventReceiver( 4512): onInputEvent MotionEvent.getDeviceId:6
V/InputEventReceiver( 4512): mInputMethodMgr.setRemotePc to false
D/VRI[MainActivity]( 4512): processPointerEvent: action: ACTION_UP, handled = true, X=905.3227, Y=438.40137
W/OnBackInvokedCallback( 4512): OnBackInvokedCallback is not enabled for the application.
W/OnBackInvokedCallback( 4512): Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
D/Dialog  ( 4512): dismiss in ... mOwnerActivity = null
D/OpenGLRenderer( 4512): endAllActiveAnimators on 0xb4000075c557b160 (RippleDrawable) with handle 0xb4000074d56861f0
D/Z##OverScrollerMifavor( 4512): SplineOverScroller mStringID = [9a8b] , this = android.widget.OverScroller$SplineOverScroller@dc59a8b
D/Z##OverScrollerMifavor( 4512): SplineOverScroller mStringID = [5768] , this = android.widget.OverScroller$SplineOverScroller@4bb5768
D/Z##OverScrollerMifavor( 4512): new SplineOverScroller.SMART_SLIDE in OverScroller. mScrollerX = android.widget.OverScroller$SplineOverScroller@dc59a8b, mScrollerY = android.widget.OverScroller$SplineOverScroller@4bb5768
D/Dialog  ( 4512): hide in ... mOwnerActivity = null
V/InputEventReceiver( 4512): onInputEvent MotionEvent.getDeviceId:6
V/InputEventReceiver( 4512): mInputMethodMgr.setRemotePc to false
D/VRI[MainActivity]( 4512): processPointerEvent: action: ACTION_DOWN, handled = true, X=271.54727, Y=2464.7502
V/InputEventReceiver( 4512): onInputEvent MotionEvent.getDeviceId:6
V/InputEventReceiver( 4512): mInputMethodMgr.setRemotePc to false
V/InputEventReceiver( 4512): onInputEvent MotionEvent.getDeviceId:6
V/InputEventReceiver( 4512): mInputMethodMgr.setRemotePc to false
V/InputEventReceiver( 4512): onInputEvent MotionEvent.getDeviceId:6
V/InputEventReceiver( 4512): mInputMethodMgr.setRemotePc to false
D/ActivityThread( 4512): ***** performPauseActivity ActivityRecord{e61e330 token=android.os.BinderProxy@2535873 {org.fcitx.fcitx5.android/org.fcitx.fcitx5.android.ui.main.MainActivity}} finished= false paused= false mFinished= false
D/ActivityThread( 4512): ***** handleStopActivity r ActivityRecord{e61e330 token=android.os.BinderProxy@2535873 {org.fcitx.fcitx5.android/org.fcitx.fcitx5.android.ui.main.MainActivity}} stopped= false paused= true
D/Dialog  ( 4512): hide in ... mOwnerActivity = null
D/Dialog  ( 4512): hide in ... mOwnerActivity = null
D/Dialog  ( 4512): hide in ... mOwnerActivity = null
D/ActivityThread( 4512): ***** handleStartActivity ActivityRecord{e61e330 token=android.os.BinderProxy@2535873 {org.fcitx.fcitx5.android/org.fcitx.fcitx5.android.ui.main.MainActivity}} stopped= true paused= true mFinished= false
W/OnBackInvokedCallback( 4512): OnBackInvokedCallback is not enabled for the application.
W/OnBackInvokedCallback( 4512): Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
I/Dialog  ( 4512): Dialog:  org.fcitx.fcitx5.android
I/Dialog  ( 4512): Dialog:  org.fcitx.fcitx5.android
D/Dialog  ( 4512): show in ... mOwnerActivity = null
D/Z##OverScrollerMifavor( 4512): SplineOverScroller mStringID = [d32e] , this = android.widget.OverScroller$SplineOverScroller@e93d32e
D/Z##OverScrollerMifavor( 4512): SplineOverScroller mStringID = [1ecf] , this = android.widget.OverScroller$SplineOverScroller@2dd1ecf
D/Z##OverScrollerMifavor( 4512): new SplineOverScroller.SMART_SLIDE in OverScroller. mScrollerX = android.widget.OverScroller$SplineOverScroller@e93d32e, mScrollerY = android.widget.OverScroller$SplineOverScroller@2dd1ecf
D/Z##OverScrollerMifavor( 4512): SplineOverScroller mStringID = [3f65] , this = android.widget.OverScroller$SplineOverScroller@2143f65
D/Z##OverScrollerMifavor( 4512): SplineOverScroller mStringID = [f43a] , this = android.widget.OverScroller$SplineOverScroller@b0df43a
D/Z##OverScrollerMifavor( 4512): new SplineOverScroller.SMART_SLIDE in OverScroller. mScrollerX = android.widget.OverScroller$SplineOverScroller@2143f65, mScrollerY = android.widget.OverScroller$SplineOverScroller@b0df43a
D/WindowClient( 4512): Add to mViews: DecorView@2342648[MainActivity], this = android.view.WindowManagerGlobal@43593e3mViews.size()=3
D/WindowClient( 4512): Add to mViews packageName:org.fcitx.fcitx5.android
D/ActivityThread( 4512): ***** performResumeActivity ActivityRecord{e61e330 token=android.os.BinderProxy@2535873 {org.fcitx.fcitx5.android/org.fcitx.fcitx5.android.ui.main.MainActivity}} mFinished= false
W/Parcel  ( 4512): Expecting binder but got null!
V/InputEventReceiver( 4512): onInputEvent MotionEvent.getDeviceId:6
V/InputEventReceiver( 4512): mInputMethodMgr.setRemotePc to false
D/VRI[MainActivity]( 4512): processPointerEvent: action: ACTION_DOWN, handled = true, X=898.51056, Y=422.15173
V/InputEventReceiver( 4512): onInputEvent MotionEvent.getDeviceId:6
V/InputEventReceiver( 4512): mInputMethodMgr.setRemotePc to false
D/VRI[MainActivity]( 4512): processPointerEvent: action: ACTION_UP, handled = true, X=898.51056, Y=422.15173
D/Dialog  ( 4512): dismiss in ... mOwnerActivity = null
D/OpenGLRenderer( 4512): endAllActiveAnimators on 0xb4000075c567e990 (RippleDrawable) with handle 0xb4000074d56107d0
D/Z##OverScrollerMifavor( 4512): SplineOverScroller mStringID = [ae12] , this = android.widget.OverScroller$SplineOverScroller@acaae12
D/Z##OverScrollerMifavor( 4512): SplineOverScroller mStringID = [c9e3] , this = android.widget.OverScroller$SplineOverScroller@d41c9e3
D/Z##OverScrollerMifavor( 4512): new SplineOverScroller.SMART_SLIDE in OverScroller. mScrollerX = android.widget.OverScroller$SplineOverScroller@acaae12, mScrollerY = android.widget.OverScroller$SplineOverScroller@d41c9e3
D/Dialog  ( 4512): hide in ... mOwnerActivity = null
V/InputEventReceiver( 4512): onInputEvent MotionEvent.getDeviceId:6
V/InputEventReceiver( 4512): mInputMethodMgr.setRemotePc to false
D/VRI[MainActivity]( 4512): processPointerEvent: action: ACTION_DOWN, handled = true, X=978.4452, Y=2314.6292
V/InputEventReceiver( 4512): onInputEvent MotionEvent.getDeviceId:6
V/InputEventReceiver( 4512): mInputMethodMgr.setRemotePc to false
D/VRI[MainActivity]( 4512): processPointerEvent: action: ACTION_UP, handled = true, X=978.4452, Y=2314.6292
D/ActivityThread( 4512): ***** performPauseActivity ActivityRecord{e61e330 token=android.os.BinderProxy@2535873 {org.fcitx.fcitx5.android/org.fcitx.fcitx5.android.ui.main.MainActivity}} finished= false paused= false mFinished= false
D/OpenGLRenderer( 4512): endAllActiveAnimators on 0xb4000075c5683d40 (RippleDrawable) with handle 0xb4000074d5685020
D/ActivityThread( 4512): ***** handleStopActivity r ActivityRecord{e61e330 token=android.os.BinderProxy@2535873 {org.fcitx.fcitx5.android/org.fcitx.fcitx5.android.ui.main.MainActivity}} stopped= false paused= true
D/Dialog  ( 4512): hide in ... mOwnerActivity = null
D/CompatibilityChangeReporter( 4512): Compat change id reported: 78294732; UID 10556; state: ENABLED
D/ActivityThread( 4512): ***** handleStartActivity ActivityRecord{e61e330 token=android.os.BinderProxy@2535873 {org.fcitx.fcitx5.android/org.fcitx.fcitx5.android.ui.main.MainActivity}} stopped= true paused= true mFinished= false
W/OnBackInvokedCallback( 4512): OnBackInvokedCallback is not enabled for the application.
W/OnBackInvokedCallback( 4512): Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
D/ActivityThread( 4512): ***** performResumeActivity ActivityRecord{e61e330 token=android.os.BinderProxy@2535873 {org.fcitx.fcitx5.android/org.fcitx.fcitx5.android.ui.main.MainActivity}} mFinished= false
I/.fcitx5.android( 4512): System.exit called, status: 10
I/AndroidRuntime( 4512): VM exiting with result code 10, cleanup skipped.
```
</details>

**截图 / Screenshots**

点击词典页面的浮动+号按钮后出现如下文件选择页面，点击词库文件后即闪退
![Screenshot_20230821_123148.jpg](https://github.com/fcitx5-android/fcitx5-android/assets/46591250/ab6491dd-724d-451e-ab25-43d682736d86)

**设备信息 / Device Infomation**

- 操作系统 / OS: Android 13 (MyOS 13)
- 应用版本 / App Version:  0.0.6-g024241cf-release

**附加信息 / Additional context**

在系统文件管理器中选择小企鹅输入法为打开方式打开细胞词库，可以正常导入词典，猜测是文件选择器的问题
使用文件选择器导入较小的txt格式可以正常导入
但较小或较大的搜狗细胞词库均会崩溃
示例测试词库： [词条数3000的词库](https://pinyin.sogou.com/dict/detail/index/9018)，或者[词条数三十万词库](https://pinyin.sogou.com/dict/detail/index/15117)

**Comment by rocka** [comment]
我自己的 Android 13 (LineageOS 20) 设备并不能复现这个现象，而且根据日志，崩溃出现在 ContentResolver 的实现里面，说不定是厂商魔改系统的问题

**Comment by gamecss** [comment]
我以前也碰到这样的情况，从所有文件找Download再找文件就好了（总之不用侧边栏里面的下载就好了）

**Comment by du33169** [comment]
> 我以前也碰到这样的情况，从所有文件找Download再找文件就好了（总之不用侧边栏里面的下载就好了）

你说的对，我测试了一下只有从侧边栏选择“下载“的词库的时候会崩溃

**Comment by rocka** [comment]
我手上的设备仍然不能复现

**Comment by rocka** [comment]
无法复现故关闭。
